title: "[Feat✨] "
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature that you would like added
      description: "Include the expected behaviour of the feature."
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: "Include the implementation/design references to escalate development process."
  - type: dropdown
    id: priority
    attributes:
      label: Request priority
      options:
        - High
        - Normal
        - Low
  - type: checkboxes
    attributes:
      label: Validation
      description: Before submitting the request, please make sure you do the following.
      options:
        - label: I have checked that there isn't already a request for the same feature to avoid creating a duplicate.
          required: true
