name: 🐞Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['Bug']
assignees: []
body:
  - type: dropdown
    id: affected-component
    attributes:
      label: Affected component
      description: Which component is affected
      options:
        - AbAccordion
        - AbAppLogo
        - AbBadge
        - AbBreadcrumbs
        - AbButton
        - AbCard
        - AbCheckbox
        - AbDateInput
        - AbDialog
        - AbObjectDiff
        - AbDivider
        - AbDrawer
        - AbField
        - AbFieldset
        - AbFileInput
        - AbFlex
        - AbForm
        - AbGrid
        - AbInput
        - AbInputController
        - AbLabel
        - AbMenu
        - AbNav
        - AbNotification
        - AbPersona
        - AbPopover
        - AbProgressBar
        - AbRadio
        - AbResult
        - AbScrollablePane
        - AbSearchbox
        - AbSelect
        - AbSkeleton
        - AbSlider
        - AbSpinner
        - AbStepper
        - AbSwitch
        - AbTable
        - AbTabs
        - AbText
        - AbTextarea
        - AbToolbar
        - AbTooltip
        
    validations:
      required: false

  - type: textarea
    id: env-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{@fluent/*}' --browsers`
      render: shell
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please provide a link to one of following browser tools based on library version:
        - React Northstar / v0 - https://codesandbox.io/s/fluent-ui-template-8ismt
        - React / v8  - https://aka.ms/fluentpen
        - React Components / v9 - https://codesandbox.io/
        - Web Components - https://codesandbox.io/

        Or a link to a repo that can reproduce the problem you ran into.

        **NOTE:**

        A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required.
        If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label.

        If no reproduction is provided after 3 days, it will be auto-closed.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      value: |
        ## Actual Behavior
        `fill this out`

        ## Expected Behavior
        fill this out
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: dropdown
    id: request-priority
    attributes:
      label: Requested priority
      options:
        - Blocking
        - High
        - Normal
        - Low
    validations:
      required: true

  - type: input
    id: products-affected
    attributes:
      label: Products/sites affected
      placeholder: (provide if applicable)

  - type: dropdown
    id: requested-help
    attributes:
      label: Are you willing to submit a PR to fix?
      options:
        - 'yes'
        - 'no'
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: The provided reproduction is a minimal reproducible example of the bug.
          required: true
