name: 🐞 Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['🐞Bug']
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A brief description to explain the bug.

  - type: dropdown
    id: package-version
    attributes: 
      label: Package version
      description: The package version used when the bug was encountered.
      options: 
        - v6.0.0
        - v6.1.0

    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      multiple: true
      label: Affected component
      description: Which component is affected by this bug.
      options:
        - AbAccordion
        - AbAppLogo
        - AbBadge
        - AbBreadcrumbs
        - AbButton
        - AbCard
        - AbCheckbox
        - AbDateInput
        - AbDialog
        - AbObjectDiff
        - AbDivider
        - AbDrawer
        - AbField
        - AbFieldset
        - AbFileInput
        - AbFlex
        - AbForm
        - AbGrid
        - AbInput
        - AbInputController
        - AbLabel
        - AbMenu
        - AbNav
        - AbNotification
        - AbPersona
        - AbPopover
        - AbProgressBar
        - AbRadio
        - AbResult
        - AbScrollablePane
        - AbSearchbox
        - AbSelect
        - AbSkeleton
        - AbSlider
        - AbSpinner
        - AbStepper
        - AbSwitch
        - AbTable
        - AbTabs
        - AbText
        - AbTextarea
        - AbToolbar
        - AbTooltip

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      placeholder: Write about what was expected.
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      placeholder: Write about what didn't work.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes: 
      label: Steps to reproduce
      placeholder: Steps to take in order to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Logs & screenshots
      placeholder: Paste any relavant logs and screenshots.

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Please ensure the following is confirmed before submitting the issue.
      options:
        - label: I have checked that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: I have attached relevant logs and/or screenshots.
          required: true
