name: "✨ New feature"
description: Describe a new feature.
title: '[feat✨]: '
labels: []
assignees: []
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature that needs to be added.
    validations:
      required: true

  - type: textarea
    id: feature-discussion-points
    attributes:
      label: Key points during the discussion of this feature.
    validations:
      required: false

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: I have checked that there isn't already an issue for the same feature to avoid creating a duplicate.
          required: true
